language: cpp

branches:
  only:
    - master

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install libace-dev
  - sudo apt-get update 

before_install:
  - sudo apt-get install libace-dev
  - sudo apt-get update 

script:
  - test -d build || mkdir build
  - test -d install || mkdir install
  - cd build
  - if [ "$CXX" == "g++" ]; then cmake -DPCH=0 -DCMAKE_BUILD_TYPE=Release -DUSE_STD_MALLOC=1 -DACE_USE_EXTERNAL=1 -DLIB_INSTALL_DIR="../install/lib" -DINCLUDE_INSTALL_DIR="../install/include" -DCMAKE_INSTALL_PREFIX=../install .. -DCMAKE_C_FLAGS_RELEASE:STRING="-march=native -O2 -DNDEBUG -finput-charset=utf-8 -fexec-charset=utf-8" -DCMAKE_CXX_FLAGS_RELEASE:STRING="-march=native -O2 -DNDEBUG -finput-charset=utf-8 -fexec-charset=utf-8"; fi
  - if [ "$CXX" == "clang++" ]; then cmake -DPCH=0 -DCMAKE_BUILD_TYPE=Release -DUSE_STD_MALLOC=1 -DACE_USE_EXTERNAL=1 -DLIB_INSTALL_DIR="../install/lib" -DINCLUDE_INSTALL_DIR="../install/include" -DCMAKE_INSTALL_PREFIX=../install .. -DCMAKE_C_FLAGS_RELEASE:STRING="-march=native -O2 -DNDEBUG -finput-charset=utf-8 -fexec-charset=utf-8" -DCMAKE_CXX_FLAGS_RELEASE:STRING="-march=native -O2 -DNDEBUG -finput-charset=utf-8 -fexec-charset=utf-8 -std=c++11"; fi
  - make -j4

notifications:
  irc:
    channels:
      - "irc.rizon.net#mangosR2"
    on_success: never
    on_failure: never
